[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.black]
line-length = 120
target-version = ['py38']
include = '''
    .*mbrl/.*\.pyi?$
    | .*experiments/.*\.pyi?$
'''
